const animeList = [
{ id:'frieren', title:'장송의 프리렌', genre:'fantasy', mood:'comfort', world:'fantasy', pace:'slow', length:'medium', score:98, symbol:'旅', image:'https://cdn.myanimelist.net/images/anime/1015/138006l.webp', tags:['판타지','힐링','여운'], summary:'마왕을 쓰러뜨린 이후의 시간을 따라가며 모험의 의미와 기억을 되짚는 감성 판타지.', reason:'조용하지만 깊은 여운과 아름다운 작화가 필요할 때 가장 안정적인 선택이에요.' },
  { id:'jjk', title:'주술회전', genre:'action', mood:'power', world:'modern', pace:'fast', length:'medium', score:94, symbol:'呪', image:'https://cdn.myanimelist.net/images/anime/1171/109222l.webp', tags:['액션','다크','능력 배틀'], summary:'저주와 주술사가 충돌하는 세계에서 펼쳐지는 빠르고 강렬한 현대 퇴마 액션.', reason:'속도감 있는 전투와 스타일리시한 연출을 원한다면 추천해요.' },
  { id:'spy-family', title:'스파이 패밀리', genre:'healing', mood:'comfort', world:'modern', pace:'balanced', length:'short', score:91, symbol:'家', image:'https://cdn.myanimelist.net/images/anime/1441/122795l.webp', tags:['코미디','가족','힐링'], summary:'스파이, 암살자, 초능력자가 가짜 가족으로 만나 진짜 같은 일상을 만들어가는 코미디.', reason:'부담 없이 웃고 싶거나 같이 보기 좋은 작품을 찾을 때 좋아요.' },
  { id:'your-lie', title:'4월은 너의 거짓말', genre:'romance', mood:'heart', world:'modern', pace:'slow', length:'medium', score:90, symbol:'音', image:'https://cdn.myanimelist.net/images/anime/1405/143284l.webp', tags:['로맨스','음악','감동'], summary:'음악을 잃은 피아노 소년이 바이올리니스트를 만나 다시 감정을 마주하는 이야기.', reason:'감정선이 진하고 음악이 오래 남는 로맨스를 보고 싶을 때 잘 맞아요.' },
  { id:'steins-gate', title:'슈타인즈 게이트', genre:'mystery', mood:'brain', world:'sf', pace:'slow', length:'medium', score:97, symbol:'時', image:'https://cdn.myanimelist.net/images/anime/1935/127974l.webp', tags:['SF','타임리프','반전'], summary:'우연한 시간 간섭 실험이 세계선을 뒤흔드는 SF 스릴러.', reason:'초반 빌드업 뒤에 터지는 강한 몰입감과 반전을 원한다면 강력 추천해요.' },
  { id:'demon-slayer', title:'귀멸의 칼날', genre:'action', mood:'power', world:'japan', pace:'fast', length:'medium', score:93, symbol:'炎', image:'https://cdn.myanimelist.net/images/anime/1286/99889l.webp', tags:['액션','일본풍','작화'], summary:'혈귀가 된 여동생을 되돌리기 위해 검사가 되는 소년의 성장 액션.', reason:'화려한 전투 연출과 일본풍 시대극 분위기를 즐기기 좋아요.' },
  { id:'apothecary', title:'약사의 혼잣말', genre:'mystery', mood:'brain', world:'japan', pace:'balanced', length:'medium', score:92, symbol:'薬', image:'https://cdn.myanimelist.net/images/anime/1708/138033l.webp', tags:['추리','궁중','캐릭터'], summary:'약학 지식과 관찰력을 가진 마오마오가 궁중 사건을 풀어가는 미스터리 드라마.', reason:'날카로운 추리와 매력적인 주인공의 티키타카를 좋아한다면 잘 맞아요.' },
  { id:'haikyu', title:'하이큐!!', genre:'healing', mood:'power', world:'modern', pace:'fast', length:'long', score:95, symbol:'翔', image:'https://cdn.myanimelist.net/images/anime/7/76014l.webp', tags:['스포츠','성장','팀워크'], summary:'작은 키의 배구 소년이 팀원들과 함께 한계를 넘어서는 청춘 스포츠 애니.', reason:'기분을 끌어올리고 싶을 때 노력과 팀워크의 에너지가 확실히 전달돼요.' },
  { id:'violet', title:'바이올렛 에버가든', genre:'healing', mood:'comfort', world:'fantasy', pace:'slow', length:'short', score:96, symbol:'便', image:'https://cdn.myanimelist.net/images/anime/1795/95088l.webp', tags:['힐링','감동','작화'], summary:'감정을 배우는 자동수기인형이 편지를 통해 사람들의 마음을 이어주는 이야기.', reason:'아름다운 영상미와 잔잔한 감동을 원할 때 최고의 선택지 중 하나예요.' },
  { id:'kaguya', title:'카구야 님은 고백받고 싶어', genre:'romance', mood:'heart', world:'modern', pace:'fast', length:'short', score:93, symbol:'恋', image:'https://cdn.myanimelist.net/images/anime/1295/106551l.webp', tags:['로맨스','코미디','두뇌전'], summary:'서로 좋아하지만 먼저 고백하지 않으려는 두 천재의 귀여운 심리전 로맨틱 코미디.', reason:'웃기면서 설레는 로맨스를 원한다면 실패 확률이 낮아요.' },
  { id:'aot', title:'진격의 거인', genre:'action', mood:'brain', world:'fantasy', pace:'fast', length:'long', score:99, symbol:'壁', image:'https://cdn.myanimelist.net/images/anime/10/47347l.webp', tags:['액션','정치극','반전'], summary:'거인에게 둘러싸인 세계의 진실을 추적하며 전쟁, 자유, 선택을 다루는 대서사시.', reason:'압도적인 스케일과 끊임없는 반전, 무거운 주제를 원할 때 추천해요.' },
  { id:'mushoku', title:'무직전생', genre:'fantasy', mood:'power', world:'fantasy', pace:'balanced', length:'long', score:89, symbol:'魔', image:'https://cdn.myanimelist.net/images/anime/1530/117776l.webp', tags:['이세계','판타지','성장'], summary:'새로운 세계에서 다시 태어난 주인공이 마법과 모험 속에서 삶을 배워가는 판타지.', reason:'정통 판타지 모험과 성장형 서사를 길게 즐기고 싶을 때 좋아요.' },
  { id:'naruto', title:'나루토', genre:'action', mood:'power', world:'japan', pace:'balanced', length:'long', score:88, symbol:'忍', image:'https://cdn.myanimelist.net/images/anime/1141/142503l.webp', tags:['닌자','성장','우정'], summary:'닌자 세계에서 인정받고 싶은 소년 나루토가 동료와 함께 성장하는 장편 액션.', reason:'왕도 성장물과 긴 호흡의 캐릭터 서사를 좋아한다면 잘 맞아요.' },
  { id:'one-piece', title:'원피스', genre:'fantasy', mood:'power', world:'fantasy', pace:'balanced', length:'long', score:97, symbol:'海', image:'https://cdn.myanimelist.net/images/anime/1244/138851l.webp', tags:['모험','해적','동료'], summary:'해적왕을 꿈꾸는 루피와 밀짚모자 일당이 바다를 누비는 대형 모험 서사.', reason:'끝없는 세계관 탐험과 동료애를 길게 즐기고 싶을 때 추천해요.' },
  { id:'death-note', title:'데스노트', genre:'mystery', mood:'brain', world:'modern', pace:'fast', length:'medium', score:96, symbol:'死', image:'https://cdn.myanimelist.net/images/anime/1079/138100l.webp', tags:['심리전','스릴러','두뇌전'], summary:'이름을 쓰면 사람이 죽는 노트를 얻은 천재와 명탐정의 치열한 심리전.', reason:'한 번 보기 시작하면 멈추기 어려운 두뇌 싸움을 원할 때 좋아요.' },
  { id:'fmab', title:'강철의 연금술사 BROTHERHOOD', genre:'fantasy', mood:'brain', world:'fantasy', pace:'balanced', length:'long', score:99, symbol:'錬', image:'https://cdn.myanimelist.net/images/anime/1208/94745l.webp', tags:['판타지','모험','완성도'], summary:'금기를 범한 형제가 잃어버린 몸을 되찾기 위해 진실을 추적하는 명작 판타지.', reason:'서사 완성도와 액션, 감동의 균형이 뛰어난 작품을 찾는다면 추천해요.' },
  { id:'cowboy-bebop', title:'카우보이 비밥', genre:'mystery', mood:'comfort', world:'sf', pace:'slow', length:'short', score:95, symbol:'星', image:'https://cdn.myanimelist.net/images/anime/4/19644l.webp', tags:['SF','느와르','재즈'], summary:'우주 현상금 사냥꾼들의 고독한 여정을 재즈와 느와르 감성으로 그린 클래식.', reason:'세련된 분위기와 에피소드형 감상을 원할 때 잘 맞아요.' },
  { id:'chainsaw-man', title:'체인소 맨', genre:'action', mood:'power', world:'modern', pace:'fast', length:'short', score:91, symbol:'鋸', image:'https://cdn.myanimelist.net/images/anime/1806/126216l.webp', tags:['액션','고어','악마'], summary:'악마와 계약한 소년 덴지가 잔혹하고도 기묘한 세계에 뛰어드는 다크 액션.', reason:'강렬한 연출과 독특한 캐릭터 감각을 원한다면 추천해요.' },
  { id:'oshi-no-ko', title:'최애의 아이', genre:'mystery', mood:'brain', world:'modern', pace:'balanced', length:'medium', score:94, symbol:'推', image:'https://cdn.myanimelist.net/images/anime/1812/134736l.webp', tags:['아이돌','미스터리','드라마'], summary:'연예계의 빛과 그림자, 환생과 복수의 미스터리를 결합한 화제작.', reason:'화려한 소재 뒤에 숨은 어두운 진실을 따라가는 이야기를 좋아하면 잘 맞아요.' },
  { id:'solo-leveling', title:'나 혼자만 레벨업', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'medium', score:90, symbol:'級', image:'https://cdn.myanimelist.net/images/anime/1801/142390l.webp', tags:['헌터','성장','액션'], summary:'최약체 헌터가 시스템의 힘으로 압도적인 성장 곡선을 그리는 액션 판타지.', reason:'빠른 성장과 시원한 전투 카타르시스를 원할 때 좋아요.' },
  { id:'mha', title:'나의 히어로 아카데미아', genre:'action', mood:'power', world:'modern', pace:'balanced', length:'long', score:89, symbol:'英', image:'https://cdn.myanimelist.net/images/anime/10/78745l.webp', tags:['히어로','성장','학원'], summary:'개성이 능력이 된 세계에서 히어로를 꿈꾸는 소년의 성장 학원 액션.', reason:'히어로물과 팀 배틀, 성장 서사를 함께 즐기고 싶다면 추천해요.' },
  { id:'mob-psycho', title:'모브사이코 100', genre:'action', mood:'comfort', world:'modern', pace:'fast', length:'short', score:94, symbol:'霊', image:'https://cdn.myanimelist.net/images/anime/8/80356l.webp', tags:['초능력','코미디','성장'], summary:'강력한 초능력을 가진 평범한 소년 모브가 감정과 성장을 배워가는 이야기.', reason:'유쾌하지만 따뜻한 성장물과 폭발적인 연출을 동시에 원할 때 좋아요.' },
  { id:'made-in-abyss', title:'메이드 인 어비스', genre:'fantasy', mood:'brain', world:'fantasy', pace:'slow', length:'medium', score:95, symbol:'淵', image:'https://cdn.myanimelist.net/images/anime/6/86733l.webp', tags:['모험','다크','미스터리'], summary:'거대한 구멍 어비스를 탐험하며 아름답고 잔혹한 비밀을 마주하는 모험 판타지.', reason:'귀여운 외형과 대비되는 깊은 미스터리와 어두운 세계관을 원할 때 추천해요.' },
  { id:'vinland', title:'빈란드 사가', genre:'action', mood:'brain', world:'japan', pace:'slow', length:'long', score:96, symbol:'剣', image:'https://cdn.myanimelist.net/images/anime/1500/103005l.webp', tags:['전쟁','복수','성장'], summary:'바이킹 시대를 배경으로 복수와 전쟁, 인간의 삶을 묵직하게 그린 역사 드라마.', reason:'무게감 있는 성장과 전쟁 서사를 보고 싶다면 잘 맞아요.' },
  { id:'bocchi', title:'봇치 더 록!', genre:'healing', mood:'comfort', world:'modern', pace:'fast', length:'short', score:92, symbol:'結', image:'https://cdn.myanimelist.net/images/anime/1448/127956l.webp', tags:['밴드','코미디','청춘'], summary:'극도로 낯가리는 소녀가 밴드 활동을 통해 조금씩 세상과 연결되는 음악 코미디.', reason:'가볍게 웃으면서도 청춘의 성장을 느끼고 싶을 때 추천해요.' },
  { id:'blue-lock', title:'블루 록', genre:'action', mood:'power', world:'modern', pace:'fast', length:'medium', score:88, symbol:'蹴', image:'https://cdn.myanimelist.net/images/anime/1258/126929l.webp', tags:['스포츠','경쟁','축구'], summary:'세계 최고의 스트라이커를 만들기 위한 극한 경쟁 프로젝트를 그린 축구 애니.', reason:'팀워크보다 생존 경쟁에 가까운 뜨거운 스포츠물을 원할 때 좋아요.' },
  { id:'horimiya', title:'호리미야', genre:'romance', mood:'heart', world:'modern', pace:'balanced', length:'short', score:90, symbol:'恋', image:'https://cdn.myanimelist.net/images/anime/1695/111486l.webp', tags:['로맨스','학원','일상'], summary:'학교와 집에서 다른 얼굴을 가진 두 사람이 가까워지는 따뜻한 학원 로맨스.', reason:'편안하고 사랑스러운 분위기의 로맨스를 찾는다면 추천해요.' },
  { id:'one-punch', title:'원펀맨', genre:'action', mood:'power', world:'modern', pace:'fast', length:'short', score:92, symbol:'拳', image:'https://cdn.myanimelist.net/images/anime/12/76049l.webp', tags:['히어로','코미디','액션'], summary:'어떤 적이든 한 방에 끝내는 히어로 사이타마의 유쾌하고 시원한 액션 코미디.', reason:'부담 없이 강력한 액션과 웃음을 동시에 원할 때 좋아요.' },
  { id:'attack-on-titan', title:'Attack on Titan', genre:'mystery', mood:'brain', world:'modern', pace:'fast', length:'medium', score:86, symbol:'進', image:'https://cdn.myanimelist.net/images/anime/10/47347l.webp', tags:['액션','수상작','드라마'], summary:'현대적인 배경에서 액션, 수상작, 드라마 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'death-note-2', title:'Death Note', genre:'mystery', mood:'brain', world:'fantasy', pace:'balanced', length:'medium', score:86, symbol:'デ', image:'https://cdn.myanimelist.net/images/anime/1079/138100l.webp', tags:['초자연','서스펜스','심리'], summary:'판타지 세계관에서 초자연, 서스펜스, 심리 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'fullmetal-alchemist-brotherhood', title:'Fullmetal Alchemist: Brotherhood', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'long', score:91, symbol:'鋼', image:'https://cdn.myanimelist.net/images/anime/1208/94745l.webp', tags:['액션','모험','드라마'], summary:'판타지 세계관에서 액션, 모험, 드라마 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'one-punch-man', title:'One-Punch Man', genre:'action', mood:'power', world:'modern', pace:'fast', length:'short', score:85, symbol:'ワ', image:'https://cdn.myanimelist.net/images/anime/12/76049l.webp', tags:['액션','코미디','Adult Cast'], summary:'현대적인 배경에서 액션, 코미디, Adult Cast 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'demon-slayer-kimetsu-no-yaiba', title:'Demon Slayer: Kimetsu no Yaiba', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'medium', score:84, symbol:'鬼', image:'https://cdn.myanimelist.net/images/anime/1286/99889l.webp', tags:['액션','수상작','초자연'], summary:'판타지 세계관에서 액션, 수상작, 초자연 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'my-hero-academia', title:'My Hero Academia', genre:'action', mood:'power', world:'modern', pace:'fast', length:'short', score:82, symbol:'僕', image:'https://cdn.myanimelist.net/images/anime/10/78745l.webp', tags:['액션','학원','Super Power'], summary:'현대적인 배경에서 액션, 학원, Super Power 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'sword-art-online', title:'Sword Art Online', genre:'romance', mood:'heart', world:'fantasy', pace:'fast', length:'medium', score:82, symbol:'ソ', image:'https://cdn.myanimelist.net/images/anime/11/39717l.webp', tags:['액션','모험','판타지'], summary:'판타지 세계관에서 액션, 모험, 판타지 감성을 중심으로 전개되는 로맨스 추천작입니다.', reason:'설렘과 감정선을 편하게 따라가고 싶을 때 잘 맞아요.' },
  { id:'hunter-x-hunter', title:'Hunter x Hunter', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'long', score:90, symbol:'H', image:'https://cdn.myanimelist.net/images/anime/1337/99013l.webp', tags:['액션','모험','판타지'], summary:'판타지 세계관에서 액션, 모험, 판타지 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'naruto-2', title:'Naruto', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'long', score:82, symbol:'ナ', image:'https://cdn.myanimelist.net/images/anime/1141/142503l.webp', tags:['액션','모험','판타지'], summary:'판타지 세계관에서 액션, 모험, 판타지 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'tokyo-ghoul', title:'Tokyo Ghoul', genre:'mystery', mood:'brain', world:'fantasy', pace:'fast', length:'short', score:82, symbol:'東', image:'https://cdn.myanimelist.net/images/anime/1498/134443l.webp', tags:['액션','판타지','호러'], summary:'판타지 세계관에서 액션, 판타지, 호러 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'jujutsu-kaisen', title:'Jujutsu Kaisen', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'medium', score:85, symbol:'呪', image:'https://cdn.myanimelist.net/images/anime/1171/109222l.webp', tags:['액션','수상작','초자연'], summary:'판타지 세계관에서 액션, 수상작, 초자연 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'your-name', title:'Your Name.', genre:'healing', mood:'comfort', world:'modern', pace:'slow', length:'short', score:88, symbol:'君', image:'https://cdn.myanimelist.net/images/anime/5/87048l.webp', tags:['수상작','드라마'], summary:'현대적인 배경에서 수상작, 드라마 감성을 중심으로 전개되는 힐링 추천작입니다.', reason:'부담 없이 보기 좋고 여운이 남는 작품을 찾을 때 잘 맞아요.' },
  { id:'attack-on-titan-season-2', title:'Attack on Titan Season 2', genre:'mystery', mood:'brain', world:'modern', pace:'fast', length:'short', score:85, symbol:'進', image:'https://cdn.myanimelist.net/images/anime/4/84177l.webp', tags:['액션','드라마','서스펜스'], summary:'현대적인 배경에서 액션, 드라마, 서스펜스 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'steins-gate-2', title:'Steins;Gate', genre:'mystery', mood:'brain', world:'sf', pace:'slow', length:'medium', score:91, symbol:'S', image:'https://cdn.myanimelist.net/images/anime/1935/127974l.webp', tags:['드라마','SF','서스펜스'], summary:'SF 세계관에서 드라마, SF, 서스펜스 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'naruto-shippuden', title:'Naruto Shippuden', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'long', score:83, symbol:'-', image:'https://cdn.myanimelist.net/images/anime/1565/111305l.webp', tags:['액션','모험','판타지'], summary:'판타지 세계관에서 액션, 모험, 판타지 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'my-hero-academia-season-2', title:'My Hero Academia Season 2', genre:'action', mood:'power', world:'modern', pace:'fast', length:'medium', score:82, symbol:'僕', image:'https://cdn.myanimelist.net/images/anime/12/85221l.webp', tags:['액션','학원','Super Power'], summary:'현대적인 배경에서 액션, 학원, Super Power 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'one-piece-2', title:'One Piece', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'medium', score:87, symbol:'O', image:'https://cdn.myanimelist.net/images/anime/1244/138851l.webp', tags:['액션','모험','판타지'], summary:'판타지 세계관에서 액션, 모험, 판타지 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'attack-on-titan-season-3', title:'Attack on Titan Season 3', genre:'mystery', mood:'brain', world:'modern', pace:'fast', length:'short', score:86, symbol:'進', image:'https://cdn.myanimelist.net/images/anime/1173/92110l.webp', tags:['액션','드라마','서스펜스'], summary:'현대적인 배경에서 액션, 드라마, 서스펜스 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'a-silent-voice', title:'A Silent Voice', genre:'healing', mood:'comfort', world:'modern', pace:'slow', length:'short', score:89, symbol:'聲', image:'https://cdn.myanimelist.net/images/anime/1122/96435l.webp', tags:['수상작','드라마','소년만화'], summary:'현대적인 배경에서 수상작, 드라마, 소년만화 감성을 중심으로 전개되는 힐링 추천작입니다.', reason:'부담 없이 보기 좋고 여운이 남는 작품을 찾을 때 잘 맞아요.' },
  { id:'attack-on-titan-season-3-part-2', title:'Attack on Titan Season 3 Part 2', genre:'mystery', mood:'brain', world:'modern', pace:'fast', length:'short', score:90, symbol:'進', image:'https://cdn.myanimelist.net/images/anime/1517/100633l.webp', tags:['액션','드라마','서스펜스'], summary:'현대적인 배경에서 액션, 드라마, 서스펜스 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'no-game-no-life', title:'No Game, No Life', genre:'fantasy', mood:'power', world:'fantasy', pace:'balanced', length:'short', score:82, symbol:'ノ', image:'https://cdn.myanimelist.net/images/anime/1074/111944l.webp', tags:['코미디','판타지','Ecchi'], summary:'판타지 세계관에서 코미디, 판타지, Ecchi 감성을 중심으로 전개되는 판타지 추천작입니다.', reason:'새로운 세계관과 모험의 재미를 느끼고 싶을 때 추천해요.' },
  { id:'code-geass-lelouch-of-the-rebellion', title:'Code Geass: Lelouch of the Rebellion', genre:'fantasy', mood:'brain', world:'sf', pace:'slow', length:'medium', score:87, symbol:'コ', image:'https://cdn.myanimelist.net/images/anime/1032/135088l.webp', tags:['수상작','드라마','SF'], summary:'SF 세계관에서 수상작, 드라마, SF 감성을 중심으로 전개되는 판타지 추천작입니다.', reason:'새로운 세계관과 모험의 재미를 느끼고 싶을 때 추천해요.' },
  { id:'re-zero-starting-life-in-another-world', title:'Re:ZERO -Starting Life in Another World-', genre:'mystery', mood:'brain', world:'fantasy', pace:'slow', length:'medium', score:82, symbol:'R', image:'https://cdn.myanimelist.net/images/anime/1522/128039l.webp', tags:['드라마','판타지','서스펜스'], summary:'판타지 세계관에서 드라마, 판타지, 서스펜스 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'your-lie-in-april', title:'Your Lie in April', genre:'romance', mood:'heart', world:'modern', pace:'slow', length:'medium', score:86, symbol:'四', image:'https://cdn.myanimelist.net/images/anime/1405/143284l.webp', tags:['드라마','로맨스','Love Polygon'], summary:'현대적인 배경에서 드라마, 로맨스, Love Polygon 감성을 중심으로 전개되는 로맨스 추천작입니다.', reason:'설렘과 감정선을 편하게 따라가고 싶을 때 잘 맞아요.' },
  { id:'my-hero-academia-season-3', title:'My Hero Academia Season 3', genre:'action', mood:'power', world:'modern', pace:'fast', length:'medium', score:82, symbol:'僕', image:'https://cdn.myanimelist.net/images/anime/1319/92084l.webp', tags:['액션','학원','Super Power'], summary:'현대적인 배경에서 액션, 학원, Super Power 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'toradora', title:'Toradora!', genre:'romance', mood:'heart', world:'modern', pace:'slow', length:'medium', score:82, symbol:'と', image:'https://cdn.myanimelist.net/images/anime/13/22128l.webp', tags:['드라마','로맨스','Love Polygon'], summary:'현대적인 배경에서 드라마, 로맨스, Love Polygon 감성을 중심으로 전개되는 로맨스 추천작입니다.', reason:'설렘과 감정선을 편하게 따라가고 싶을 때 잘 맞아요.' },
  { id:'mob-psycho-100', title:'Mob Psycho 100', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'short', score:85, symbol:'モ', image:'https://cdn.myanimelist.net/images/anime/8/80356l.webp', tags:['액션','코미디','초자연'], summary:'판타지 세계관에서 액션, 코미디, 초자연 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'noragami', title:'Noragami', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'short', score:82, symbol:'ノ', image:'https://cdn.myanimelist.net/images/anime/1886/128266l.webp', tags:['액션','초자연','Mythology'], summary:'판타지 세계관에서 액션, 초자연, Mythology 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'erased', title:'Erased', genre:'mystery', mood:'brain', world:'modern', pace:'balanced', length:'short', score:83, symbol:'僕', image:'https://cdn.myanimelist.net/images/anime/10/77957l.webp', tags:['미스터리','서스펜스','심리'], summary:'현대적인 배경에서 미스터리, 서스펜스, 심리 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'attack-on-titan-final-season', title:'Attack on Titan: Final Season', genre:'mystery', mood:'brain', world:'modern', pace:'fast', length:'medium', score:88, symbol:'進', image:'https://cdn.myanimelist.net/images/anime/1000/110531l.webp', tags:['액션','드라마','서스펜스'], summary:'현대적인 배경에서 액션, 드라마, 서스펜스 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'akame-ga-kill', title:'Akame ga Kill!', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'medium', score:82, symbol:'ア', image:'https://cdn.myanimelist.net/images/anime/1429/95946l.webp', tags:['액션','판타지','Gore'], summary:'판타지 세계관에서 액션, 판타지, Gore 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'assassination-classroom', title:'Assassination Classroom', genre:'action', mood:'power', world:'modern', pace:'fast', length:'medium', score:82, symbol:'暗', image:'https://cdn.myanimelist.net/images/anime/5/75639l.webp', tags:['액션','코미디','학원'], summary:'현대적인 배경에서 액션, 코미디, 학원 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'the-seven-deadly-sins', title:'The Seven Deadly Sins', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'medium', score:82, symbol:'七', image:'https://cdn.myanimelist.net/images/anime/8/65409l.webp', tags:['액션','모험','판타지'], summary:'판타지 세계관에서 액션, 모험, 판타지 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'bleach', title:'Bleach', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'long', score:82, symbol:'B', image:'https://cdn.myanimelist.net/images/anime/1541/147774l.webp', tags:['액션','모험','초자연'], summary:'판타지 세계관에서 액션, 모험, 초자연 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'angel-beats', title:'Angel Beats!', genre:'fantasy', mood:'power', world:'fantasy', pace:'slow', length:'short', score:82, symbol:'A', image:'https://cdn.myanimelist.net/images/anime/1244/111115l.webp', tags:['드라마','판타지','학원'], summary:'판타지 세계관에서 드라마, 판타지, 학원 감성을 중심으로 전개되는 판타지 추천작입니다.', reason:'새로운 세계관과 모험의 재미를 느끼고 싶을 때 추천해요.' },
  { id:'haikyu-2', title:'Haikyu!!', genre:'action', mood:'power', world:'modern', pace:'fast', length:'medium', score:84, symbol:'ハ', image:'https://cdn.myanimelist.net/images/anime/7/76014l.webp', tags:['스포츠','학원','Team Sports'], summary:'현대적인 배경에서 스포츠, 학원, Team Sports 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'the-promised-neverland', title:'The Promised Neverland', genre:'mystery', mood:'brain', world:'modern', pace:'balanced', length:'short', score:85, symbol:'約', image:'https://cdn.myanimelist.net/images/anime/1830/118780l.webp', tags:['미스터리','서스펜스','심리'], summary:'현대적인 배경에서 미스터리, 서스펜스, 심리 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'konosuba-god-s-blessing-on-this-wonderful-worl', title:'KonoSuba: God\'s Blessing on This Wonderful World!', genre:'action', mood:'power', world:'fantasy', pace:'balanced', length:'short', score:82, symbol:'こ', image:'https://cdn.myanimelist.net/images/anime/1895/142748l.webp', tags:['모험','코미디','판타지'], summary:'판타지 세계관에서 모험, 코미디, 판타지 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'the-future-diary', title:'The Future Diary', genre:'mystery', mood:'brain', world:'fantasy', pace:'fast', length:'medium', score:82, symbol:'未', image:'https://cdn.myanimelist.net/images/anime/13/33465l.webp', tags:['액션','초자연','서스펜스'], summary:'판타지 세계관에서 액션, 초자연, 서스펜스 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'sword-art-online-ii', title:'Sword Art Online II', genre:'romance', mood:'heart', world:'fantasy', pace:'fast', length:'medium', score:82, symbol:'ソ', image:'https://cdn.myanimelist.net/images/anime/1223/121999l.webp', tags:['액션','모험','판타지'], summary:'판타지 세계관에서 액션, 모험, 판타지 감성을 중심으로 전개되는 로맨스 추천작입니다.', reason:'설렘과 감정선을 편하게 따라가고 싶을 때 잘 맞아요.' },
  { id:'cowboy-bebop-2', title:'Cowboy Bebop', genre:'action', mood:'power', world:'sf', pace:'fast', length:'medium', score:88, symbol:'カ', image:'https://cdn.myanimelist.net/images/anime/4/19644l.webp', tags:['액션','수상작','SF'], summary:'SF 세계관에서 액션, 수상작, SF 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'blue-exorcist', title:'Blue Exorcist', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'medium', score:82, symbol:'青', image:'https://cdn.myanimelist.net/images/anime/10/75195l.webp', tags:['액션','초자연','Mythology'], summary:'판타지 세계관에서 액션, 초자연, Mythology 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'parasyte-the-maxim', title:'Parasyte: The Maxim', genre:'mystery', mood:'brain', world:'sf', pace:'fast', length:'medium', score:83, symbol:'寄', image:'https://cdn.myanimelist.net/images/anime/3/73178l.webp', tags:['액션','호러','SF'], summary:'SF 세계관에서 액션, 호러, SF 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'neon-genesis-evangelion', title:'Neon Genesis Evangelion', genre:'mystery', mood:'brain', world:'sf', pace:'slow', length:'medium', score:84, symbol:'新', image:'https://cdn.myanimelist.net/images/anime/1314/108941l.webp', tags:['실험적','수상작','드라마'], summary:'SF 세계관에서 실험적, 수상작, 드라마 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'spirited-away', title:'Spirited Away', genre:'action', mood:'power', world:'fantasy', pace:'balanced', length:'short', score:88, symbol:'千', image:'https://cdn.myanimelist.net/images/anime/6/79597l.webp', tags:['모험','수상작','판타지'], summary:'판타지 세계관에서 모험, 수상작, 판타지 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'violet-evergarden', title:'Violet Evergarden', genre:'healing', mood:'comfort', world:'modern', pace:'slow', length:'short', score:87, symbol:'ヴ', image:'https://cdn.myanimelist.net/images/anime/1795/95088l.webp', tags:['드라마'], summary:'현대적인 배경에서 드라마 감성을 중심으로 전개되는 힐링 추천작입니다.', reason:'부담 없이 보기 좋고 여운이 남는 작품을 찾을 때 잘 맞아요.' },
  { id:'chainsaw-man-2', title:'Chainsaw Man', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'short', score:84, symbol:'チ', image:'https://cdn.myanimelist.net/images/anime/1806/126216l.webp', tags:['액션','판타지','Gore'], summary:'판타지 세계관에서 액션, 판타지, Gore 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'rascal-does-not-dream-of-bunny-girl-senpai', title:'Rascal Does Not Dream of Bunny Girl Senpai', genre:'romance', mood:'heart', world:'fantasy', pace:'slow', length:'short', score:82, symbol:'青', image:'https://cdn.myanimelist.net/images/anime/1301/93586l.webp', tags:['드라마','로맨스','초자연'], summary:'판타지 세계관에서 드라마, 로맨스, 초자연 감성을 중심으로 전개되는 로맨스 추천작입니다.', reason:'설렘과 감정선을 편하게 따라가고 싶을 때 잘 맞아요.' },
  { id:'dr-stone', title:'Dr. Stone', genre:'action', mood:'power', world:'modern', pace:'balanced', length:'medium', score:83, symbol:'ド', image:'https://cdn.myanimelist.net/images/anime/1613/102576l.webp', tags:['모험','코미디','소년만화'], summary:'현대적인 배경에서 모험, 코미디, 소년만화 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'code-geass-lelouch-of-the-rebellion-r2', title:'Code Geass: Lelouch of the Rebellion R2', genre:'fantasy', mood:'brain', world:'sf', pace:'slow', length:'medium', score:89, symbol:'コ', image:'https://cdn.myanimelist.net/images/anime/1088/135089l.webp', tags:['수상작','드라마','SF'], summary:'SF 세계관에서 수상작, 드라마, SF 감성을 중심으로 전개되는 판타지 추천작입니다.', reason:'새로운 세계관과 모험의 재미를 느끼고 싶을 때 추천해요.' },
  { id:'kaguya-sama-love-is-war', title:'Kaguya-sama: Love is War', genre:'romance', mood:'heart', world:'modern', pace:'balanced', length:'short', score:84, symbol:'か', image:'https://cdn.myanimelist.net/images/anime/1295/106551l.webp', tags:['코미디','로맨스','학원'], summary:'현대적인 배경에서 코미디, 로맨스, 학원 감성을 중심으로 전개되는 로맨스 추천작입니다.', reason:'설렘과 감정선을 편하게 따라가고 싶을 때 잘 맞아요.' },
  { id:'death-parade', title:'Death Parade', genre:'mystery', mood:'brain', world:'fantasy', pace:'slow', length:'short', score:82, symbol:'デ', image:'https://cdn.myanimelist.net/images/anime/5/71553l.webp', tags:['드라마','판타지','서스펜스'], summary:'판타지 세계관에서 드라마, 판타지, 서스펜스 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'my-hero-academia-season-4', title:'My Hero Academia Season 4', genre:'action', mood:'power', world:'modern', pace:'fast', length:'medium', score:82, symbol:'僕', image:'https://cdn.myanimelist.net/images/anime/1412/107914l.webp', tags:['액션','학원','Super Power'], summary:'현대적인 배경에서 액션, 학원, Super Power 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'black-clover', title:'Black Clover', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'long', score:82, symbol:'ブ', image:'https://cdn.myanimelist.net/images/anime/2/88336l.webp', tags:['액션','판타지','소년만화'], summary:'판타지 세계관에서 액션, 판타지, 소년만화 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'tokyo-ghoul-a', title:'Tokyo Ghoul √A', genre:'mystery', mood:'brain', world:'fantasy', pace:'fast', length:'short', score:82, symbol:'東', image:'https://cdn.myanimelist.net/images/anime/1889/123307l.webp', tags:['액션','판타지','호러'], summary:'판타지 세계관에서 액션, 판타지, 호러 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'spy-x-family', title:'Spy x Family', genre:'action', mood:'power', world:'modern', pace:'fast', length:'short', score:84, symbol:'S', image:'https://cdn.myanimelist.net/images/anime/1441/122795l.webp', tags:['액션','수상작','코미디'], summary:'현대적인 배경에서 액션, 수상작, 코미디 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'one-punch-man-season-2', title:'One-Punch Man Season 2', genre:'action', mood:'power', world:'modern', pace:'fast', length:'short', score:82, symbol:'ワ', image:'https://cdn.myanimelist.net/images/anime/1247/122044l.webp', tags:['액션','코미디','Adult Cast'], summary:'현대적인 배경에서 액션, 코미디, Adult Cast 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'jojo-s-bizarre-adventure-2012', title:'JoJo\'s Bizarre Adventure (2012)', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'medium', score:82, symbol:'ジ', image:'https://cdn.myanimelist.net/images/anime/3/40409l.webp', tags:['액션','모험','초자연'], summary:'판타지 세계관에서 액션, 모험, 초자연 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'kill-la-kill', title:'Kill la Kill', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'medium', score:82, symbol:'キ', image:'https://cdn.myanimelist.net/images/anime/1464/111943l.webp', tags:['액션','코미디','판타지'], summary:'판타지 세계관에서 액션, 코미디, 판타지 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'fairy-tail', title:'Fairy Tail', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'long', score:82, symbol:'F', image:'https://cdn.myanimelist.net/images/anime/5/18179l.webp', tags:['액션','모험','판타지'], summary:'판타지 세계관에서 액션, 모험, 판타지 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'vinland-saga', title:'Vinland Saga', genre:'action', mood:'power', world:'japan', pace:'fast', length:'medium', score:88, symbol:'ヴ', image:'https://cdn.myanimelist.net/images/anime/1500/103005l.webp', tags:['액션','모험','드라마'], summary:'일본풍 분위기에서 액션, 모험, 드라마 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'darling-in-the-franxx', title:'DARLING in the FRANXX', genre:'romance', mood:'heart', world:'sf', pace:'slow', length:'medium', score:82, symbol:'ダ', image:'https://cdn.myanimelist.net/images/anime/1614/90408l.webp', tags:['드라마','로맨스','SF'], summary:'SF 세계관에서 드라마, 로맨스, SF 감성을 중심으로 전개되는 로맨스 추천작입니다.', reason:'설렘과 감정선을 편하게 따라가고 싶을 때 잘 맞아요.' },
  { id:'another', title:'Another', genre:'mystery', mood:'brain', world:'modern', pace:'balanced', length:'short', score:82, symbol:'ア', image:'https://cdn.myanimelist.net/images/anime/4/75509l.webp', tags:['호러','미스터리','Gore'], summary:'현대적인 배경에서 호러, 미스터리, Gore 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'demon-slayer-kimetsu-no-yaiba-the-movie-mugen-', title:'Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'short', score:85, symbol:'劇', image:'https://cdn.myanimelist.net/images/anime/1704/106947l.webp', tags:['액션','초자연','역사'], summary:'판타지 세계관에서 액션, 초자연, 역사 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'soul-eater', title:'Soul Eater', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'long', score:82, symbol:'ソ', image:'https://cdn.myanimelist.net/images/anime/1071/149486l.webp', tags:['액션','코미디','판타지'], summary:'판타지 세계관에서 액션, 코미디, 판타지 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'gurren-lagann', title:'Gurren Lagann', genre:'action', mood:'power', world:'sf', pace:'balanced', length:'medium', score:86, symbol:'天', image:'https://cdn.myanimelist.net/images/anime/4/5123l.webp', tags:['모험','수상작','SF'], summary:'SF 세계관에서 모험, 수상작, SF 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'the-rising-of-the-shield-hero', title:'The Rising of the Shield Hero', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'medium', score:82, symbol:'盾', image:'https://cdn.myanimelist.net/images/anime/1490/101365l.webp', tags:['액션','모험','드라마'], summary:'판타지 세계관에서 액션, 모험, 드라마 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'charlotte', title:'Charlotte', genre:'healing', mood:'comfort', world:'modern', pace:'slow', length:'short', score:82, symbol:'C', image:'https://cdn.myanimelist.net/images/anime/1826/147276l.webp', tags:['드라마','학원','Super Power'], summary:'현대적인 배경에서 드라마, 학원, Super Power 감성을 중심으로 전개되는 힐링 추천작입니다.', reason:'부담 없이 보기 좋고 여운이 남는 작품을 찾을 때 잘 맞아요.' },
  { id:'overlord', title:'Overlord', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'short', score:82, symbol:'オ', image:'https://cdn.myanimelist.net/images/anime/1945/136600l.webp', tags:['액션','모험','판타지'], summary:'판타지 세계관에서 액션, 모험, 판타지 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' },
  { id:'psycho-pass', title:'Psycho-Pass', genre:'mystery', mood:'brain', world:'sf', pace:'fast', length:'medium', score:83, symbol:'サ', image:'https://cdn.myanimelist.net/images/anime/1314/142015l.webp', tags:['액션','미스터리','SF'], summary:'SF 세계관에서 액션, 미스터리, SF 감성을 중심으로 전개되는 미스터리 추천작입니다.', reason:'반전과 추리, 긴장감 있는 이야기를 보고 싶을 때 좋아요.' },
  { id:'food-wars-shokugeki-no-soma', title:'Food Wars! Shokugeki no Soma', genre:'healing', mood:'comfort', world:'modern', pace:'balanced', length:'medium', score:82, symbol:'食', image:'https://cdn.myanimelist.net/images/anime/1444/148976l.webp', tags:['요리','Ecchi','학원'], summary:'현대적인 배경에서 요리, Ecchi, 학원 감성을 중심으로 전개되는 힐링 추천작입니다.', reason:'부담 없이 보기 좋고 여운이 남는 작품을 찾을 때 잘 맞아요.' },
  { id:'demon-slayer-kimetsu-no-yaiba-entertainment-di', title:'Demon Slayer: Kimetsu no Yaiba Entertainment District Arc', genre:'action', mood:'power', world:'fantasy', pace:'fast', length:'short', score:87, symbol:'鬼', image:'https://cdn.myanimelist.net/images/anime/1908/120036l.webp', tags:['액션','초자연','역사'], summary:'판타지 세계관에서 액션, 초자연, 역사 감성을 중심으로 전개되는 액션 추천작입니다.', reason:'시원한 전개와 몰입감 있는 장면을 원할 때 추천해요.' }
];

const profiles = [
  { id:'solo', name:'혼자 몰입', avatar:'🎧', palette:['#8b5cf6','#38bdf8'], prefer:{mood:'brain', pace:'slow'} },
  { id:'family', name:'가족과 함께', avatar:'🍿', palette:['#fb7185','#facc15'], prefer:{mood:'comfort', length:'short'} },
  { id:'action', name:'액션 덕후', avatar:'⚔️', palette:['#f97316','#dc2626'], prefer:{mood:'power', pace:'fast'} },
  { id:'romance', name:'설렘 모드', avatar:'🌸', palette:['#ff8fb8','#a78bfa'], prefer:{mood:'heart', world:'modern'} }
];

const genreLabels = { action:'액션', healing:'힐링', romance:'로맨스', mystery:'미스터리', fantasy:'판타지' };
let currentFilter = 'all';
let activeProfile = localStorage.getItem('anipick-profile') || 'solo';
let watchlist = JSON.parse(localStorage.getItem('anipick-watchlist-v2') || '[]');

const $ = selector => document.querySelector(selector);
const $$ = selector => [...document.querySelectorAll(selector)];
const pickRandom = (items = animeList) => items[Math.floor(Math.random() * items.length)];
const findAnime = id => animeList.find(anime => anime.id === id);

function saveWatchlist(){ localStorage.setItem('anipick-watchlist-v2', JSON.stringify(watchlist)); }
function animeStyle(anime){ return `--p1:${anime.palette?.[0] || '#8b5cf6'};--p2:${anime.palette?.[1] || '#38bdf8'};`; }
function poster(anime){
  return `<div class="poster real-poster" style="${animeStyle(anime)}" data-symbol="${anime.symbol}">
    <img src="${anime.image}" alt="${anime.title} 공식 커버 이미지" loading="lazy" referrerpolicy="no-referrer" />
    <div class="poster-shade"></div>
    <div class="relative z-10 flex min-h-[15rem] flex-col justify-between p-5">
      <div class="flex flex-wrap gap-2">${anime.tags.map(t=>`<span class="badge">${t}</span>`).join('')}</div>
      <div><p class="text-sm font-black uppercase tracking-[.22em] text-white/80">match base ${anime.score}</p><h3 class="mt-2 font-kr text-3xl font-black text-white drop-shadow">${anime.title}</h3></div>
    </div>
  </div>`;
}
function addButton(id, label = '+'){ return `<button class="icon-button" type="button" data-add="${id}" aria-label="찜하기">${label}</button>`; }
function trackEvent(name, params = {}){
  window.AniPickAnalytics?.track?.(name, params);
}
function animePayload(anime){
  return anime ? { anime_id: anime.id, anime_title: anime.title, anime_genre: anime.genre } : {};
}

function renderHero(anime = recommendByProfile()[0]?.anime || pickRandom()){
  $('#heroPick').innerHTML = `${poster(anime)}<div class="mt-5 flex items-start justify-between gap-4"><div><p class="kicker">today's quiet pick</p><h2 class="font-kr text-3xl font-black">${anime.title}</h2></div>${addButton(anime.id)}</div><p class="mt-4 leading-7 text-[var(--muted)]">${anime.summary}</p><p class="mt-4 rounded-2xl border border-[var(--line)] bg-black/10 p-4 text-sm leading-6">추천 이유: ${anime.reason}</p>`;
}

function renderProfiles(){
  $('#profileGrid').innerHTML = profiles.map(p => `<button class="profile-card ${p.id===activeProfile?'active':''}" data-profile="${p.id}" type="button"><div class="avatar" style="--p1:${p.palette[0]};--p2:${p.palette[1]};">${p.avatar}</div><strong class="mt-4 block font-kr text-xl font-black">${p.name}</strong><small class="mt-1 block text-[var(--muted)]">${profileDescription(p)}</small></button>`).join('');
  const p = profiles.find(item => item.id === activeProfile);
  $('#activeProfileLabel').textContent = `현재 프로필: ${p.name} · 총 ${animeList.length}개 작품`;
}
function profileDescription(p){ return {solo:'몰입도와 반전 중심 추천',family:'편하게 같이 보기 좋은 추천',action:'빠른 전개와 전투 중심 추천',romance:'설렘과 감정선 중심 추천'}[p.id]; }

function scoreAnime(anime, answers){
  let score = anime.score;
  if(anime.mood === answers.mood) score += 26;
  if(anime.world === answers.world) score += 18;
  if(anime.pace === answers.pace) score += 14;
  if(anime.length === answers.length) score += 12;
  const profile = profiles.find(p=>p.id===activeProfile);
  Object.entries(profile.prefer).forEach(([key,value]) => { if(anime[key] === value) score += 10; });
  return score;
}
function getAnswers(){ return Object.fromEntries(new FormData($('#surveyForm')).entries()); }
function recommendByProfile(){
  const profile = profiles.find(p=>p.id===activeProfile);
  const defaults = { mood: profile.prefer.mood || 'comfort', world: profile.prefer.world || 'modern', pace: profile.prefer.pace || 'balanced', length: profile.prefer.length || 'medium' };
  return animeList.map(anime => ({ anime, score: scoreAnime(anime, defaults) })).sort((a,b)=>b.score-a.score);
}
function renderSurveyResult(answers = null){
  const selected = answers || getAnswers();
  const ranked = animeList.map(anime => ({ anime, score: scoreAnime(anime, selected) })).sort((a,b)=>b.score-a.score);
  const top = ranked[0];
  const percent = Math.min(99, Math.round((top.score / 170) * 100));
  $('#surveyResult').innerHTML = `<p class="kicker">your best match</p><div class="grid gap-6 md:grid-cols-[.82fr_1fr] md:items-center">${poster(top.anime)}<div><h3 class="font-kr text-3xl font-black">${top.anime.title}</h3><p class="mt-3 text-[var(--muted)]">${top.anime.summary}</p><div class="mt-5"><div class="mb-2 flex justify-between text-sm font-black"><span>취향 매칭률</span><span>${percent}%</span></div><div class="match-meter"><span style="width:${percent}%"></span></div></div><p class="mt-4 rounded-2xl border border-[var(--line)] bg-black/10 p-4 text-sm leading-6">${top.anime.reason}</p>${addButton(top.anime.id, '＋ 찜')}</div></div><div class="mt-6 grid gap-3 sm:grid-cols-2">${ranked.slice(1,5).map(({anime,score})=>`<button class="watch-card text-left" data-hero="${anime.id}" type="button"><strong>${anime.title}</strong><small class="mt-1 block text-[var(--muted)]">후보 점수 ${score}</small></button>`).join('')}</div>`;
  return { top, percent, selected };
}

function renderGrid(){
  const items = currentFilter === 'all' ? animeList : animeList.filter(anime => anime.genre === currentFilter);
  $('#animeGrid').innerHTML = items.map(anime => `<article class="anime-card">${poster(anime)}<div class="p-3"><div class="mt-1 flex items-start justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-[.2em] text-[var(--accent)]">${genreLabels[anime.genre]}</p><h3 class="mt-1 font-kr text-xl font-black">${anime.title}</h3></div>${addButton(anime.id)}</div><p class="mt-3 min-h-[4.5rem] text-sm leading-6 text-[var(--muted)]">${anime.summary}</p></div></article>`).join('');
}
function renderWatchlist(){
  const items = watchlist.map(findAnime).filter(Boolean);
  if(!items.length){ $('#watchlistItems').innerHTML = `<div class="watch-card sm:col-span-2 lg:col-span-3 text-[var(--muted)]">아직 찜한 작품이 없습니다. 추천 카드의 + 버튼을 눌러 저장해보세요.</div>`; return; }
  $('#watchlistItems').innerHTML = items.map(anime => `<article class="watch-card"><div class="flex items-start justify-between gap-4"><div><p class="kicker !mb-1">saved</p><h3 class="font-kr text-xl font-black">${anime.title}</h3></div><button class="rounded-full border border-[var(--line)] px-3 py-1 text-sm font-black" data-remove="${anime.id}" type="button">삭제</button></div><p class="mt-3 text-sm leading-6 text-[var(--muted)]">${anime.reason}</p></article>`).join('');
}
function addToWatchlist(id){ if(!watchlist.includes(id)){ watchlist.push(id); saveWatchlist(); renderWatchlist(); trackEvent('watchlist_add', animePayload(findAnime(id))); } }
function removeFromWatchlist(id){ const anime = findAnime(id); watchlist = watchlist.filter(item => item !== id); saveWatchlist(); renderWatchlist(); trackEvent('watchlist_remove', animePayload(anime)); }

function setTheme(theme, options = {}){ document.documentElement.dataset.theme = theme; localStorage.setItem('anipick-theme', theme); const label = theme === 'dark' ? '🌙 Dark' : '☀️ Light'; $$('#themeToggle,#themeToggleMobile').forEach(btn=>{ if(btn) btn.textContent = label; }); if(!options.silent) trackEvent('theme_change', { theme }); }
function toggleTheme(){ setTheme(document.documentElement.dataset.theme === 'dark' ? 'light' : 'dark'); }
function bindEvents(){
  $('#menuButton')?.addEventListener('click', e => { const menu = $('#mobileMenu'); const open = !menu.classList.contains('hidden'); menu.classList.toggle('hidden'); e.currentTarget.setAttribute('aria-expanded', String(!open)); trackEvent('mobile_menu_toggle', { open: String(!open) }); });
  $$('#themeToggle,#themeToggleMobile').forEach(btn=>btn?.addEventListener('click', toggleTheme));
  $('#profileGrid').addEventListener('click', e => { const card = e.target.closest('[data-profile]'); if(!card) return; activeProfile = card.dataset.profile; localStorage.setItem('anipick-profile', activeProfile); renderProfiles(); renderSurveyResult(); renderHero(); trackEvent('profile_select', { profile: activeProfile }); });
  $$('.filter-chip').forEach(btn=>btn.addEventListener('click',()=>{ $$('.filter-chip').forEach(c=>c.classList.remove('active')); btn.classList.add('active'); currentFilter=btn.dataset.filter; renderGrid(); trackEvent('genre_filter', { filter: currentFilter }); }));
  $('#surveyForm').addEventListener('submit', e => { e.preventDefault(); const answers = getAnswers(); const result = renderSurveyResult(answers); trackEvent('survey_submit', Object.assign({}, answers, { match_percent: result.percent }, animePayload(result.top.anime))); $('#surveyResult').scrollIntoView({behavior:'smooth', block:'center'}); });
  $('#randomHeroButton').addEventListener('click',()=>{ const anime = pickRandom(); renderHero(anime); trackEvent('random_pick', animePayload(anime)); });
  $('#clearWatchlist').addEventListener('click',()=>{ const count = watchlist.length; watchlist=[]; saveWatchlist(); renderWatchlist(); trackEvent('watchlist_clear', { removed_count: count }); });
  document.body.addEventListener('click', e => {
    const nav = e.target.closest('a[href^="#"]'); const add=e.target.closest('[data-add]'); const rem=e.target.closest('[data-remove]'); const hero=e.target.closest('[data-hero]');
    if(nav) trackEvent('nav_click', { target: nav.getAttribute('href'), label: nav.textContent.trim().slice(0, 40) });
    if(add){ const original = add.textContent; addToWatchlist(add.dataset.add); add.textContent='✓'; setTimeout(()=>{ add.textContent = original; },800); }
    if(rem) removeFromWatchlist(rem.dataset.remove);
    if(hero) { const anime = findAnime(hero.dataset.hero); renderHero(anime); trackEvent('recommendation_candidate_open', animePayload(anime)); $('#top').scrollIntoView({behavior:'smooth'}); }
  });
}

function init(){
  const themeVersion = 'red-white-v1';
  if(localStorage.getItem('anipick-theme-version') !== themeVersion){
    localStorage.setItem('anipick-theme-version', themeVersion);
    localStorage.setItem('anipick-theme', 'light');
  }
  setTheme(localStorage.getItem('anipick-theme') || 'light', { silent: true });
  renderProfiles(); renderHero(); renderSurveyResult(); renderGrid(); renderWatchlist(); bindEvents();
}
document.addEventListener('DOMContentLoaded', init);
